name: Build

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: 0 0 * * *

jobs:
  bochscpu:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - {os: windows-latest, arch: x64}
          - {os: ubuntu-latest, arch: x64}
          - {os: macos-latest, arch: x64}
    runs-on: ${{ matrix.variant.os }}
    name: ${{ matrix.variant.os }} / ${{ matrix.variant.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: microsoft/setup-msbuild@v1
      if: matrix.variant.os == 'windows-latest'

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.variant.os == 'windows-latest'

    - name: Build BochsCPU (Windows)
      if: matrix.variant.os == 'windows-latest'
      continue-on-error: true
      shell: powershell
      run: |
        bash -c 'sh prep.sh; cd Bochs/bochs; sh .conf.cpu-msvc;'
        cd Bochs/bochs
        nmake
        cd ../..
        ls -Recurse
        mkdir lib
        cp -Verbose Bochs/bochs/cpu/libcpu.a lib/cpu.a
        cp -Verbose Bochs/bochs/cpu/fpu/libfpu.a lib/fpu.a
        cp -Verbose Bochs/bochs/cpu/avx/libavx.a lib/avx.a
        cp -Verbose Bochs/bochs/cpu/cpudb/libcpudb.a lib/cpudb.a

    - name: Build BochsCPU (Linux & MacOS)
      if: matrix.variant.os != 'windows-latest'
      shell: bash
      run: |
        sh prep.sh
        cd Bochs/bochs
        sh .conf.cpu
        make || true
        cd ../..
        ls -alR
        mkdir lib
        cp --verbose Bochs/bochs/cpu/libcpu.a lib/
        cp --verbose Bochs/bochs/cpu/fpu/libfpu.a lib/
        cp --verbose Bochs/bochs/cpu/avx/libavx.a lib/
        cp --verbose Bochs/bochs/cpu/cpudb/libcpudb.a lib/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bochscpu-build-${{ matrix.variant.os }}-${{ matrix.variant.arch }}
        path: lib
